// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZLxwb2zHds3BbrmObN8CMZM3qu23La44',
    appId: '1:165774025525:web:c009d751695340e9c0e27c',
    messagingSenderId: '165774025525',
    projectId: 'pajak-app-f9298',
    authDomain: 'pajak-app-f9298.firebaseapp.com',
    storageBucket: 'pajak-app-f9298.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJwj81LT1Bj0Tm4UzU3h1XwBT8UDT5gEg',
    appId: '1:165774025525:android:1db45201a82cf4c1c0e27c',
    messagingSenderId: '165774025525',
    projectId: 'pajak-app-f9298',
    storageBucket: 'pajak-app-f9298.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGK_wCMadEcvpbZ2DymccqDGAq_lnQZnI',
    appId: '1:165774025525:ios:f51350f2ad313698c0e27c',
    messagingSenderId: '165774025525',
    projectId: 'pajak-app-f9298',
    storageBucket: 'pajak-app-f9298.appspot.com',
    iosBundleId: 'com.fiveHacks.pajakApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGK_wCMadEcvpbZ2DymccqDGAq_lnQZnI',
    appId: '1:165774025525:ios:8c40c81b275502c2c0e27c',
    messagingSenderId: '165774025525',
    projectId: 'pajak-app-f9298',
    storageBucket: 'pajak-app-f9298.appspot.com',
    iosBundleId: 'com.example.pajakApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZLxwb2zHds3BbrmObN8CMZM3qu23La44',
    appId: '1:165774025525:web:d58b4ef7213565efc0e27c',
    messagingSenderId: '165774025525',
    projectId: 'pajak-app-f9298',
    authDomain: 'pajak-app-f9298.firebaseapp.com',
    storageBucket: 'pajak-app-f9298.appspot.com',
  );
}
